### ISSUE TITLE
SQLitePersistentBlobCache Flush / Vacuum hang when awaited

### ISSUE THREAD

**Issue by chrisriesgo** [akavache/Akavache#179]
If I await a call to Flush() or Vacuum() on my SQLitePersistentBlobCache, the app just hangs. 

e.g. - `await BlobCache.Secure.Flush();`

Am I missing something, should I not await this call, or is this a bug?

**Comment by tempywritescode** [comment]
I'm also hitting this in 4.1.0. Also happens only on Android, and not reliably. Any further insight into what's causing this?

As a hack I'm throwing a timeout on it and hoping nothing too bad happens when I ignore the timeout, so far so good...

**Comment by GPugnet** [comment]
I am facing the same issue, on Xamarin and iOS, with akavache 4.1.0.

**Comment by hampos** [comment]
I am also facing this issue, on Xamarin.Mac 1.12 and Akavache 4.1.1.

**Comment by flagbug** [comment]
This should be fixed with https://github.com/akavache/Akavache/pull/254
