### ISSUE TITLE
Error while installing in Xamarin via NuGet

### ISSUE THREAD

**Issue by tkowalczyk** [akavache/Akavache#200]
During the installation I am getting this error:
Unable to resolve dependency 'Akavache.SQLite3 (= 4.1.0)'.
What it could be? I am using Xamarin.Studio on Mac

**Comment by jiujiu1123** [comment]
What I did is manually add the dependency your self then add akavache nuget packge

**Comment by tkowalczyk** [comment]
Yes I have installed sqlite with my own and now it is working, but I think it should as dependency on NuGet package ;)
THX
