### ISSUE TITLE
Overriding IFilesystemProvider - am I doing it wrong?

### ISSUE THREAD

**Issue by RocketPop** [akavache/Akavache#202]
As a user of the Nuget package - I'm trying to make a tool where Akavache will store it's files in a particular folder. I am trying to ONLY use public interfaces and not change Akavache source. It's not a multi-platform tool - just desktop.

I see what I want is %90+ the same as SimpleFilesystemProvider. But I can't derive from that class without a bunch of copy and paste to replicate internal or private helper code. I thought I could wrap an instance of SimpleFilesystemProvider up in my own WrapedFilesystemProvider so I can return my own locations in the path accessors and just pass thru all other calls to the wrapped instance. 

I then register WrappedFilesystemProvider before setting ApplicationName like so:
`Locator.CurrentMutable.Register(() => wrappedProvider, typeof(IFilesystemProvider), null);`

Unfortunately the register code in Akavache overrides my registration with a fresh SimpleFilesystemProvider - breaking my hopes of overriding the paths :) 
I've also tried setting up the Locator after setting ApplicationName, but the blob instances seem to cache the first locator they got at startup (even though they seem lazy use/create most other stuff)

Am I going about this the right way? Should the Akavache registrations code check to see if the registered type already has a singleton setup and just use that?  Maybe the blob instance fetch the services they need only when they are about to write? Or I could be missing something obvious. Not sure the "right way" to approach this and I'm mildly stuck. (If I get put on the right track I can make a PR for the result)

**Comment by flagbug** [comment]
Just set the blobcaches to a new value like 'BlobCache.LocalMachine = new SqliteBlobCache("path/to/the/database/file.db");'

**Comment by paulcbetts** [comment]
^^ What @flagbug said - the `BlobCache` static class is just Some Good Advice, you can always create the cache classes explicitly
