### ISSUE TITLE
Data format change?

### ISSUE THREAD

**Issue by RocketPop** [akavache/Akavache#204]
I'm trying to update my iOS app with akavache 4.1.0 from 4.0.4 - I have a released app with previously downloaded data that needs to be compatible. All data was (and is still) downloaded into the cache with
 `            var bytes = await BlobCache.LocalMachine.DownloadUrl(key, url, null, false);`
Images from the cache now no longer load correctly with 4.1.0

I look into the databases with AkavacheExplorer. I see when reading objects downloaded with 4.0.4 it seems they were encoded and wrapped in JSON like:
`    {
        "Value": "iVBORw0KGgoAAAANSUhEUgAAAJwAA (snip 28k)"
    }`

But images downloaded with 4.1.0 just have the raw PNG or JPG bytes with no encoding or json
`�PNG (snip 28k)`

Did the behavior of DownloadUrl() change?

**Comment by flagbug** [comment]
Yup, see https://github.com/akavache/Akavache/pull/197

**Comment by RocketPop** [comment]
Ok thanks. Sorry for the dupe report! How can I work around this? I'll have a mix of "legacy" data and new data in our cache. Do I need to get the raw bytes with Get() every time and peek for '{' and switch to load image versus decoding that blob myself now?

**Comment by paulcbetts** [comment]
@RocketPop I honestly would let the cache just fail and redownload

**Comment by RocketPop** [comment]
Hmm. Well I can't really do that since the data is already "installed" in the cache - I can't tell without peeking at the data if it's "new" and good or "old" and needs a refresh. I chose to use the DownloadUrl(key, url) variant so that after the initial setup phase where I pre-fill my cache, I don't have to bother keeping the urls around and so I work in offline mode, etc.  Imagine "skins" for a family of match-3 games or whatever. My keys are something like "gamelogo" and "tileset" . The game installer detects what game it is - then sets up a big list of fetches to install from the right game asset server and never looks back at urls :) This co-exists with dynamic fetched data like news, offers, facebook crap, etc.  So we potentially have mixed new and old blob format data.

My new plan (unless there are better ideas!) is to have a 1-time data conversion pass in the new app update and look at every single key and try to figure out if it's one of those encoded images and "decode" it out of that JSON wrapper, then force re-insert it. I assume that it is just just base64 encoded in that JSON?

**Comment by paulcbetts** [comment]
>  I assume that it is just just base64 encoded in that JSON?

No, it's BSON encoded - the way to do it is

```cs
var bytes = await theCache.GetObject<byte[]>(theKey);
await theCache.Insert(theKey, bytes);
```

**Comment by RocketPop** [comment]
Thanks Paul & flagbug - I'll fix that up on my end.
