### ISSUE TITLE
nuget file has old version of splat

### ISSUE THREAD

**Issue by gordonwatts** [akavache/Akavache#206]
The nuget file has 1.3.3 specified as the required version of splat. If you start with an empty project and just include Akavache, you end up with 1.3.3 installed. However, it looks like it is built against 1.6.0 as you get a DLL load error - claiming that 1.3.3 is too old. I think the nuget nuspec file just needs to be updated to reflect the version it is built against.

**Comment by shiftkey** [comment]
@gordonwatts can you attach the `packages.config` that you get after installing plain Akavache, to confirm which versions are included for the dependencies?

**Comment by gordonwatts** [comment]
Repro Steps:

1. Create new blank solution (you can't have a solution that already has a modern version of Splat in any other project or nuget will choose that by default. This is what saves you most of the time).
2. Create a new blank universal app
3. Using nuget, put Akavache in both the windows phone and the windows store app
4. Look at the packages.config.

**Comment by shiftkey** [comment]
@gordonwatts  :heart_eyes: thanks!

**Comment by gordonwatts** [comment]
And thanks for this tool - I sat down to design a local cache, and then thought I should look on the internet... and minus one feature, this is exactly what I needed (I will need to poll my data every 10 minutes). I can't tell you how nice it is to find software like this ready to play with and use! So... Thanks!
