### ISSUE TITLE
Progress support when downloading images

### ISSUE THREAD

**Issue by promontis** [akavache/Akavache#209]
Hi Paul,

Thinking of adding progress support when downloading images as I'd like to show some progress information while images are downloading (on a slow connection). 

Currently, you are using WebRequest. Would it be ok if I'd were to use HttpClient (GetByteArrayAsync more specifically)? By using HttpClient, I could create some overloads accepting a HttpClientHandler and use the ModernHttpClient implementation of receiving progress. 

Would you agree on such an implementation or do you see any issues with this?

**Comment by paulcbetts** [comment]
@promontis Maybe instead just create an extension method that would convert an `HttpContent` into an `IBitmap`? That way you can do progress at the HttpClient layer then at the end just call `ToBitmap()` on the content and you've got an image

**Comment by promontis** [comment]
@paulcbetts I forgot the mention that I would like to overload DownloadUrl() and LoadImageFromUrl(). So taking caching into account. The challenge is not in the downloading and converting it to an IBitmap, but rather the hook with Akavache. 

I could create a different extension class, based on HttpClient. But I do like the HttpClient pipeline a lot more, with it's ability to inject handlers and such. I think the current implementation of DownloadUrl (and extensions using that method) lacks extensibility in that area.

**Comment by paulcbetts** [comment]
Remember that DownloadUrl and friends aren't core functionality (i.e. they don't require access to internal methods / secret handshakes), they're just helper extensions to solve common problems. You can totally write your own more Fancy methods on top / copy-paste the source into your app and mess with it

Really, the super flexible / progress friendly version belongs in paulcbetts/Fusillade, the Akavache version is just the crappy "get stuff done" version
