### ISSUE TITLE
Live Observables

### ISSUE THREAD

**Issue by nsainaney** [akavache/Akavache#213]
Hi,
I'm new to Rx and have been researching how to keep Observables alive but haven't found anything. I'm using Akavache together with ReactiveUI.

I have a request to fetch an object like so:

``` C#
BlobCache.UserAccount.GetObject<IEnumerable<Event>>("events")
                .Catch(Observable.Return(new List<Event>().AsEnumerable()))
                .ObserveOn(RxApp.MainThreadScheduler)
                .Subscribe(async events =>
                {
                    await Page.DisplayAlert("Loaded", "Yay!", "OK");
                }, async exception =>
                {
                    await Page.DisplayAlert("Error", exception.Message, "OK");
                }, async delegate
                {
                    await Page.DisplayAlert("Done", ":(", "OK");
                });
```

And I notice that "Loaded" and "Done" pops up which means the subscription completes and does not stay alive. I was hoping that when I do a BlockCache.UserAccount.Insert<IEnumerable<Event>>("events", ...); that the Subscribe would fire again but this does not seem to be the case. Am I missing something?

Thanks

**Comment by paulcbetts** [comment]
When do you expect Insert to fire again? The Observable is telling you that the operation has completed.

**Comment by shiftkey** [comment]
I think this is comes down to a mis-understanding about Akavache. Let me see if I can explain it.

The observable created when invoking `GetObject` is alive for however long it takes to retrieve the object from the backing store. Once you have that object, it signals completion.

If you were expecting the observable to stay alive so that an `InsertObject` for the same key on another thread would signal this observable again, that's unfortunately not part of Akavache's design.

It might be an interesting experiment to add on top of Akavache but I'm not sure how feasible it would be.

**Comment by paulcbetts** [comment]
@nsainaney For the vast majority of APIs in Akavache, you can just think of it as returning Task<T>, just `await` the result (if it gives you problems, you probably need a `using System.Reactive.Concurrency;`

**Comment by nsainaney** [comment]
Here's my use case. I retrieve objects from a remote server and am using Akavache to cache them (in case the phone is offline etc.). However, there are other user's updating these objects on the server in which case, I use SignalR or some other push notification to notify my app of the change. This notification happens in some background thread which updates the Akavache cache however, I now have to also figure out how to notify any other threads that are holding on to the object.

@shiftkey Perhaps it's a misunderstanding. @paulcbetts I understand now that it's about a single return and Rx and Task are used to keep the multithreading clean.

Thanks for a great library! I'm sure I'll figure something out though I'm reasonably sure the above will be a common use case where apps are getting push updates from servers.
