### ISSUE TITLE
Akavache.sqlite3 appears to hang if I don't "initialize" Akavache

### ISSUE THREAD

**Issue by PureWeen** [akavache/Akavache#216]
Running on WP8.1 and I also noticed this running against Android

I have a ReactiveCommand that I create like this in the Viewmodel constructor

```
			RefreshTripCommand = ReactiveCommand.CreateAsyncObservable((x) =>
			{
				return BlobCache.LocalMachine
						.GetOrFetchObject<TripStatus>("GetSomeThings",
							() =>
							{
								return Task.FromResult(new TripStatus());
							}
						);
			});
```

I execute it from the VIEW constructor like this

```
			this.WhenAnyValue(x => x.ViewModel.RefreshTripCommand)
				.SelectMany(x => x.ExecuteAsync())
				.Subscribe();
```

The app just hangs at this stack trace

```
mscorlib.ni.dll!System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle waitableSafeHandle, long millisecondsTimeout, bool hasThreadAffinity, bool exitContext)	Unknown
 	mscorlib.ni.dll!System.Threading.WaitHandle.WaitOne(long timeout, bool exitContext)	Unknown
 	mscorlib.ni.dll!System.Threading.WaitHandle.WaitOne(int millisecondsTimeout, bool exitContext)	Unknown
 	mscorlib.ni.dll!System.Threading.WaitHandle.WaitOne()	Unknown
 	System.Reactive.Linq.DLL!System.Reactive.Linq.QueryLanguage.LastOrDefaultInternal<System.Reactive.Unit>(System.IObservable<System.Reactive.Unit> source, bool throwOnEmpty)	Unknown
 	System.Reactive.Linq.DLL!System.Reactive.Linq.QueryLanguage.Wait<System.Reactive.Unit>(System.IObservable<System.Reactive.Unit> source)	Unknown
 	System.Reactive.Linq.DLL!System.Reactive.Linq.Observable.Wait<System.Reactive.Unit>(System.IObservable<System.Reactive.Unit> source)	Unknown
 	Akavache.Sqlite3.DLL!Akavache.Sqlite3.Registrations.Register.AnonymousMethod__0()	Unknown
 	mscorlib.ni.dll!System.Lazy<Akavache.IBlobCache>.CreateValue()	Unknown
 	mscorlib.ni.dll!System.Lazy<Akavache.IBlobCache>.LazyInitValue()	Unknown
 	mscorlib.ni.dll!System.Lazy<Akavache.IBlobCache>.Value.get()	Unknown
 	Akavache.Sqlite3.DLL!Akavache.Sqlite3.Registrations.Register.AnonymousMethod__1()	Unknown
 	Splat.DLL!Splat.ModernDependencyResolver.GetService(System.Type serviceType, string contract)	Unknown
 	Splat.DLL!Splat.DependencyResolverMixins.GetService<Akavache.IBlobCache>(Splat.IDependencyResolver This, string contract)	Unknown
 	Akavache.DLL!Akavache.BlobCache.LocalMachine.get()	Unknown

```

In Registration.cs this is the line that's hanging
```
fs.CreateRecursive(fs.GetDefaultLocalMachineCacheDirectory()).Wait();
```

If I change it to this
```
Task.Run(() => fs.CreateRecursive(fs.GetDefaultLocalMachineCacheDirectory()).Wait()).Wait();
```

Then it executes the code for that observable and it goes on its marry way...

Or if I just throw this into the VM constructor
```
BlobCache.LocalMachine
					.GetOrFetchObject<TripStatus>("RandomStuff",
						() =>
						{
							return Task.FromResult(new TripStatus());
						}
					);
```

As a dummy operation then everything after that runs smoothly

Am I missing an initialization step? Or doing something else incorrectly?

**Comment by PureWeen** [comment]
Alright I was able to simplify the problem down to the interaction that's happening. The first call I ever make to Akavache is occurring from a ReactiveCommand... So from what I can tell  the Wait that happens the first time Akavache is called
```
fs.CreateRecursive(fs.GetDefaultLocalMachineCacheDirectory()).Wait();
```
is being queue'd after the ReactiveCommand by the Scheduler but the ReactiveCommand is never able to finish because the Wait is blocking....  (At least that's what extrapolated from source stepping RX)

Here's some simplified code to illustrate the interaction that's happening
```
 //This represents the Reactive Command Observable.Create wrapper
            var ret = Observable.Return<Unit>(Unit.Default).SelectMany(_ =>
                {
                    Debug.WriteLine("second example starting");
                    //This represents the wait happening inside the Akavache Registration
                    Observable.Range(0, 1)
                        .Take(1)
                        .Wait();

                   //the call never makes it here
                    Debug.WriteLine("second example completed");
                    return Observable.Return<Unit>(Unit.Default);
                });
                
            //this runs fine
            Observable.Range(0, 1)
                .Take(1)
                .Wait();
            Debug.WriteLine("First example completed");
            ret.Subscribe();
```

So my guess is that any time the first call to Akavache is made  from inside an already scheduled observable you'll see this problem

The couple of ways I've tried that seem to resolve this are

1)  What I mentioned above wrapping the wait inside a task so it's not deadlocked
```
Task.Run(() => fs.CreateRecursive(fs.GetDefaultLocalMachineCacheDirectory()).Wait()).Wait();
```

2) in the registration setting a subscribeon for the wait operation
```
fs.CreateRecursive(fs.GetDefaultLocalMachineCacheDirectory()).SubscribeOn(BlobCache.TaskpoolScheduler).Wait();
```

Which I think in principal are the same thing

**Comment by martingemme** [comment]
@PureWeen Could you provide a sample app with Windows 8.1 Universal (or WP8.1) running with Akavache? I would desperately want to look into it!

**Comment by PureWeen** [comment]
@martingemme  try initializing the BlobCache you are using with some dummy values in the App.Xaml.cs or in your boot trapping process ... Which gets the cache's initalized

So I just do  these

await BlobCache.LocalMachine.InsertObject("Initialized", true);
await BlobCache.InMemory.InsertObject("Initialized", true);

Which gets the stuff initialized so it doesn't lock up

**Comment by dominik-weber** [comment]
Could you please release a new build so I can check if the proposed fix solves this issue?

**Comment by ghuntley** [comment]
New build is available on myget
