### ISSUE TITLE
Windows Phone 8 Xamarin.Forms Exception

### ISSUE THREAD

**Issue by coonmoo** [akavache/Akavache#217]
Dear Paul,

I'm currently having a problem with my Xamarin.Forms application when it comes to Windows Phone 8.

The following error message is thrown when I deploy and run on a device:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Akavache.BlobCache' threw an exception. ---> System.Exception: Failed to initialize Akavache properly. Do you have a reference to Akavache.dll?

I selected "ARM" and "Debug" from the Configuration Manager for the application.

The dll files getting correcttly deployed to the device, so that shouldn't be an issue.

Any ideas on this?

**Comment by paulcbetts** [comment]
I haven't heard of this before, you probably need to debug it

**Comment by paulcbetts** [comment]
If I had to guess, you probably don't actually reference Akavache in your WP8 app, only in the shared PLib library

**Comment by coonmoo** [comment]
Thanks for the fast response!

It seemed that the PCL from another referenced assembly was copied to the Wp8 application and deleted the Wp8 one.

It's working now.
