### ISSUE TITLE
awaiting IObservable<T>

### ISSUE THREAD

**Issue by scolestock** [akavache/Akavache#218]
This isn't really an akavache issue per se - I'm just curious how usage of akavache intersects with the advice to have library methods call ConfigureAwait(false).  It appears that the extension methods don't provide for this.  Am I missing something ?

**Comment by paulcbetts** [comment]
If you want to do that, you can call `someMethod.ToTask().ConfigureAwait(false)`

**Comment by scolestock** [comment]
Much appreciated - missed that.
