### ISSUE TITLE
Xamarin.Mac 2.0, LocalMachine cache not being created on app launch, which never succeeds.

### ISSUE THREAD

**Issue by theofanis** [akavache/Akavache#222]
We use all 3 caches in our app. UserAccount and Secret are created as expected, but LocalMachine is missing. This happens in 1 out of 4 Macbooks we use for our tests, 3 out of 4 work as expected and all 3 caches are there right after launching the app.

The app probably throws a native exception, since we define a handler for AppDomain.CurrentDomain.UnhandledException in AppDelegate constructor, but our logs still show nothing and as per Xamarin's documentation, a native exception won't get logged.

Further investigating the problem, after trying to launch the app the path `/Users/<username>/.local/share/<appname>` doesn't exist. We changed permissions for `.local` folder but the app still doesn't launch successfully.

After manually creating `/Users/<username>/.local/share/<appname>/BlobCache` (the OS asked for user's credentials) the app manages to successfully launch and do its job.

@paulcbetts Should we check for the existence of this directory and create it on our own in AppDelegate's constructor?

**Comment by theofanis** [comment]
EDIT: It appears that the Macbook in question had this difference versus the ones that worked as expected.

`~/.local/share/` didn't have any permissions granted to the User. Adding those permissions and trying to launch the app, it works.

**Comment by paulcbetts** [comment]
:+1: :dancer: :sparkles:
