### ISSUE TITLE
Xamarin.Mac 2.0 support?

### ISSUE THREAD

**Issue by ludovicthomas** [akavache/Akavache#223]
Is there any plan to support Xamarin.Mac soon?

Today, if we create a Xamarin.Mac 2.0 project, and we add Akavache package, there is an error message saying "Mono.Posix" dependency cannot be found. It is referenced inside the csproj of the Akavache.Xamarin.Mac.csproj file.

Thanks a lot for the feedback.

**Comment by paulcbetts** [comment]
The tricky thing about Xamarin.Mac is that there are now like 3 different Xamarin.Mac build settings - we support the .NET 4.5-based one, not the Xamarin.Mobile based one

**Comment by theofanis** [comment]
Our Xamarin.Mac project targetting .NET 4.5, works fine with Akavache.

**Comment by ludovicthomas** [comment]
Thanks both for the feedback, the issue is that we are using the Xamarin.Mobile based one. I will try using the second one, but it seems to produce a bigger binary.
