### ISSUE TITLE
Windows 10 compatibility

### ISSUE THREAD

**Issue by theofanis** [akavache/Akavache#227]
I didn't have the time to thoroughly test this, but our WPF app doesn't work in Windows 10 Preview. The last version before we employ Akavache, works just fine.

I initialize Akavache on the application startup, but the caches' files never get created and I see my app changing its status to Suspended in task manager, before completely ending after a couple of seconds.

Unfortunately the app logs don't contain any error information and there isn't any unhandled exception AFAIK.

I'm building a temporary dev setup on Windows 10 Preview to try and test this more, but if you have any info on this, please share.

/cc @paulcbetts 

Edit: Just saw https://github.com/ericsink/SQLitePCL.raw/issues/44 so I guess there's no solution for this yet.

Edit 2: Replacing the `sqlite3.dll` with the one from http://www.sqlite.org/2015/sqlite-dll-win32-x86-3081002.zip everything works as expected. I replaced both dlls in `x86` and `x64` folders and tested on Windows 10 build 10122 64-bit.

**Comment by lehne** [comment]
Having this problem but in Windows 7 for a WPF app.

**Comment by ghuntley** [comment]
UWP + Akavache works, make sure you upgrade to latest SQLite and read this https://github.com/ghuntley/repros/tree/master/nuget/TransitiveRefs to work around a nuget resolution issue.

**Comment by AuroraDysis** [comment]
"suppressParent": "none" is help, Thank you @ghuntley
