### ISSUE TITLE
Akavache not working on Windows 8.1 Universal

### ISSUE THREAD

**Issue by martingemme** [akavache/Akavache#230]
I’m trying to make work Akavache in a `Windows 8.1 Universal`, but it seems (after lot of testing) that Akavache isn't working. I followed the Xamarin Evolve seminar of @paulcbetts even though his sample only includes iOS and Android (why no love for WP?)

To make sure that it is not related to my architecture, I did an empty solution that has all the necessary packages and requirements (VC++ for both platforms), and I still get the same issue. This is a blocker for me since I want all my queries to be cached.

Here's a quick peak at the code used:

``` c#
BlobCache.ApplicationName = "MyApp"; // In AppBootstrapper`

// In My ViewModel
SubmitCommand = ReactiveCommand.CreateAsyncTask(async _ =>
{
    var isTrue = await BlobCache.UserAccount.GetOrFetchObject("login_credentials",
        async () => await Task.FromResult(true)
    );
    // My Code never goes further than this
    // Other interesting stuff
    return isTrue;
});

SubmitCommand.Subscribe(isTrue => { // Nothing to see here  });

SubmitCommand.ThrownExceptions.Subscribe(ex => {  UserError.Throw(ex.Message, ex); });

// In The View
ViewModel = new MainPageViewModel();
this.BindCommand(ViewModel, x => x.SubmitCommand, x => x.SubmitCommand);

public MainPageViewModel ViewModel
{
    get { return (MainPageViewModel)GetValue(ViewModelProperty); }
    set { SetValue(ViewModelProperty, value); }
}
public static readonly DependencyProperty ViewModelProperty =
    DependencyProperty.Register("ViewModel", typeof(MainPageViewModel), typeof(MainPage), new PropertyMetadata(null));

object IViewFor.ViewModel
{
    get { return ViewModel; }
    set { ViewModel = (MainPageViewModel)value; }
}
```

I'm using RXUI 6.5 (latest) within a Windows 8.1 Universal, latest Akavache, Splat, Refit, Fusillade.

Thanks for your help!

**Comment by martingemme** [comment]
After some debug, I decided to pull Akavache, link the dummy solution to Akavache's dll and now I get to SQLite.cs, line 3129 with: Additional information: Something went wrong in the build configuration.  This is the bait assembly, which is for referencing by portable libraries, and should never end up part of the app.  Reference the appropriate platform assembly instead.
The code looks like:
```
public static Result Open(string filename, out Sqlite3DatabaseHandle db, int flags, IntPtr zVfs)
{
#if USE_WP8_NATIVE_SQLITE
	return (Result)Sqlite3.sqlite3_open_v2(filename, out db, flags, "");
#else
	return (Result)Sqlite3Raw.sqlite3_open_v2(filename, out db, flags, null); // Exception happens here
#endif
}
```
So... what's missing? Which assembly am I not referencing?

**Comment by martingemme** [comment]
Another update: I found out that SQLite.raw isn't included in the requirements and when installed, Windows 8.1 is working for me. Now Windows Phone 8.1 isn't working

**Comment by martingemme** [comment]
After some more debug, I was able to make work WinRT. Now Windows Phone 8.1 (Non-Silverlight/Jupiter) isn't working at all. It seems that I can't access (even with Akavache's Master) the Registrations method of Akavache.Sqlite3 and I result in a TypeInitializationException.

**Comment by gordonwatts** [comment]
Have you set to the x86 architecture? I think sqllite requires that, or, at least, a single arch rather than "Any CPU" which is the default.

**Comment by martingemme** [comment]
I did put x86 and VC++ has mentioned on Akavache's GitHub, but the real problem was SQLitePCL.raw_basic version 0.8.0 was installed automatically.

Of course for now 0.7.0 (what Akavache Master uses) works, but Akavache project should consider the post on SQLitePCL.raw GitHub's Readme.md (There's another NuGet package called SQLitePCL.raw_basic. What is it??)

That's the old package ID. With the 0.8.0 release, I transitioned to just 'SQLitePCL.raw' as the package ID (without the _basic suffix). Eventually I may stop publishing updates to the old ID. For now, the package gets published under both IDs and they are identical.)))

But for me, v0.8.0 of both basic and without aren't working with Akavache with my testing, so it would be important to take note for futur Akavache Updates!

**Comment by gordonwatts** [comment]
Perhaps the maintainers would think about reopening this to fix the nuspec files so it works out of the box? Or something similar? It seems like the SQLlite folks violated symantic versioning..

**Comment by martingemme** [comment]
I agree with @gordonwatts and I hope it eliminates confusion!

**Comment by martingemme** [comment]
Well, seems like I only hid the problem. In Fact, I actually removed Sqlite3 and it worked using the InMemory cache. I tried putting Akavache.Sqlite3 back in the project, now my app locks up after the first "GetObject" that i'm doing.

Anybody has an idea?

**Comment by martingemme** [comment]
For the record, I copied Registrations from Akavache.Sqlite3 in my application and I call it after BlobCache.ApplicationName and it works (the caching, fetch, etc). In the meantime, I'll have this class (exact same as https://github.com/akavache/Akavache/blob/3c1431250ae94d25cf7ac9637528f4445b131317/Akavache.Sqlite3/Registrations.cs) hardcoded.
