### ISSUE TITLE
Windows 10 UAP - TypeInitializationException

### ISSUE THREAD

**Issue by sebastianhaba** [akavache/Akavache#234]
Setting BlobCache.ApplicationName throws System.TypeInitializationException on Windows 10.

Message: Could not load file or assembly 'Splat, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by martingemme** [comment]
Is Splat referenced in your project? Your Splat version is 1.6.2 or 1.6.0?

**Comment by FTPFL007** [comment]
Thanks for the email,The following image have been attached at the GitHub for your ‎review as follow:![img_20150803_034722](https://cloud.githubusercontent.com/assets/12671617/9027950/999ba34c-3992-11e5-92ec-11279ae4ce67.jpg)Thanks you for your kind efforts and public contribution.Sincerely,NaywinFtpfl007@outlook.com                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: sebastianhabaSent: Sunday, August 2, 2015 17:28To: akavache/AkavacheReply To: akavache/AkavacheSubject: [Akavache] Windows 10 UAP - TypeInitializationException (#234)Setting BlobCache.ApplicationName throws System.TypeInitializationException on Windows 10.

Message: Could not load file or assembly 'Splat, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

—Reply to this email directly or view it on GitHub.

**Comment by minhlucnd** [comment]
I problem same. I test Windows 10 **x86** **LocalMachine** success but swich to Windows 10 Mobile **x86** **Mobile Emulator 10** throw exception : 
Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E

**Comment by tomverhoeff** [comment]
Any comments on this issue? Seeing the same problem as @minhlucnd in our UAP. The x86 version runs fine, but deploying to Windows 10 for Mobile fails. Hope to find time to dive into this later this week and will report back.

**Comment by mjracca** [comment]
What helps me is to update Splat library

**Comment by AuroraDysis** [comment]
It needs to modify project.lock.json manually to change splat 1.3.3 to 1.6.2 and change locked to true. And I add the reference **SQLite for  Universal App Platform** and all things looks fine. But I doesn't test **x86 Mobile Emulator 10**.

**Comment by RobTSchroed** [comment]
My initial error:
The type initializer for 'SQLitePCL.raw' threw an exception. Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

My Fix:
Here are the versions of everything that seem to work with UWP (at least for me) and cause the above error to go away:
Akavache 4.1.2
Akavache.sqlite3 4.1.2
Microsoft.NETCore.UniversalWindowsPlatform 5.1.0
Xamarin.Forms 2.2.0.45
SqlitePCL.raw_basic 0.8.6
Splat 1.6.0
Visual C++ 2015 Runtime for Universal Windows Platform 14.0

***Notice that we don't need the SQLite for Universal Windows Platform anymore *****
As of Windows 10 SDK Build 10586, SQLite is INCLUDED!
https://blogs.windows.com/buildingapps/2015/12/03/windows-10-build-10586-sdk-breakdown/ 

Good Luck!

**Comment by DennisWelu** [comment]
Thanks @RobTSchroed that helped. I think the salient point from https://github.com/ericsink/SQLitePCL.raw/issues/44 is that SqlitePCL.raw_basic 0.8.5 is the min required for that lib.
