### ISSUE TITLE
LoadImageFromUrl and ToNative in Xamarin.Forms

### ISSUE THREAD

**Issue by vkoppaka** [akavache/Akavache#242]
Is it possible to use Akavache's LoadImageFromUrl to cache images on to the device and retrieve them later on? 

I tried calling BlobCache.LocalMachine.LoadImageFromUrl(url) but in a PCL context, it does not have a ToNative() extension available to convert the loaded image to an ImageSource. Is there a different call I should be making when in a PCL (Xamarin.Forms) to get the store image which can be used to bind to a Image widget?

Thanks!

**Comment by ThomasKIT** [comment]
I think the official and proper way would be to use Splat and the IBitmap Extension [1, 2],
this will give you the ToNative() Extension.

   BlobCache.LocalMachine.LoadImageFromUrl(url, false, 200, 183)
       .ObserveOnDispatcher()
       .Subscribe(new Action<Splat.IBitmap>(pic => { 
           ImageView.Source = pic.ToNative();
        }), ex => Debug.WriteLine(ex));

If you want to use XF ImageSource functionality you could do something like I did using an ImageStream [3], but I didn't try to convert the Bitmap to an ImageStream.

       ImageSource.FromStream(() => ImageStream)
---
[1] - https://github.com/paulcbetts/splat
[2] - https://github.com/paulcbetts/splat/blob/e923476a84d4954e4aa6804afee0186b12fb5836/Splat/Xaml/Bitmaps.cs#L138
[3] - https://forums.xamarin.com/discussion/46808/imagesource-to-stream#latest

**Comment by vkoppaka** [comment]
Thanks @ThomasKIT. Akavache.Sqlite3 Nuget package has a dependency on Splat. So I already have Splat referenced, but I don't see ToNative() extension. I will give your streamable image source a try.

**Comment by ThomasKIT** [comment]
Well if you check the second link i posted, this is the actual content of the ToNative method:
 
   return ((BitmapSourceBitmap)This).inner;

Just try it if you can't resolve your Splat reference.

**Comment by vkoppaka** [comment]
Interesting @ThomasKIT . I think source and Nuget package may be out of sync. Here is what VS thinks of the ToNative() extension (and you can see Splat in references towards the right). I manually added using Splat just to make sure if R# is not picking up on extensions but no luck.
![tonative](https://cloud.githubusercontent.com/assets/486458/9398244/bf34dbc6-4759-11e5-9c49-a33a3b85b1ec.png)

Also, I decompiled the Splat.dll from Nuget and It doesn't seem to have BitmapMixins class at all
![bitmap_mixin](https://cloud.githubusercontent.com/assets/486458/9398261/f818923e-4759-11e5-9518-ecff312a605b.png)

@paulcbetts any suggestions?

**Comment by paulcbetts** [comment]
Add Splat directly to your app, you're looking at the wrong version (the PLib one)

**Comment by FTPFL007** [comment]
I am travelling today, I definitely try to catch up with leads I appreciate your help.
Thank you Paul. 
Date: Thu, 20 Aug 2015 21:09:46 -0700

**Comment by FTPFL007** [comment]
I am travelling today, I definitely try to catch up with leads I appreciate your help.
Thank you Mr. Thomas..
 
Date: Thu, 20 Aug 2015 16:39:35 -0700

**Comment by Letibee** [comment]
@vkoppaka 

Xamarin forms images are actually cached automatically for you, I've been using this method for quite a while now and it does indeed cache. 

Source : http://developer.xamarin.com/guides/cross-platform/xamarin-forms/working-with/images/

I'm also attempting to use Akavache with Xamarin.Froms but came upon a different issue #238 I'm guessing you don't have this issue?

**Comment by vkoppaka** [comment]
@Letibee 

Xamarin.Forms Image caching only applies to already "seen" (or visited) images. Meaning if you have images on a detail page which has not been visited yet, images that are supposed to be shown on the detail (if different from others) are not cached. Hence, I am looking for options cache them all by myself.

@paulcbetts 
Apologize if I am not following your suggestion correctly. I already have Splat referenced, the only other package I see on Nuget is a package targeting NET40. Am I missing something. Thanks so much for your help!

**Comment by FTPFL007** [comment]
Thank you gentlemen for all the help and guidance's. All the above are well noted.
I be start practicing on it as soon as i am return from my trip. You all have a nice weekend.

**Comment by flagbug** [comment]
If this is still a problem, let me know and I'll reopen this
