### ISSUE TITLE
Is Akavache inefficient in this case?

### ISSUE THREAD

**Issue by Mittchel** [akavache/Akavache#247]
Hi,

Akavache looks really great and I would like to thank @paulcbetts for this incredible contribution :-)

I do have one question whether Akavache is inefficient or not in the particular case I'm working on.

Let's say I have a List<Person> and I would like to cache them all using Akavache, this will be stored as a blob right? If I later would like to retrieve a specific Person from the stored blob this means that I have to retrieve (thus deserializing) the whole list(blob) before I can grab a specific Person stored in that blob. Is this correct? If so, doesn't this make it inefficient in comparison with regular SQLite.NET table storage? With SQLite.NET I am actually able to retrieve a specific object without retrieving the whole list.
 
Please correct me if I am wrong..

Thanks in advance!

**Comment by paulcbetts** [comment]
Nope! Instead of storing the list as a blob, you can store each element _in_ the list as a blob, then request them. The optimizer will make this run at a similar speed to querying it directly.

**Comment by Mittchel** [comment]
@paulcbetts Do you maybe have some small sample code how to handle this in the correct way?

**Comment by Mittchel** [comment]
@paulcbetts Do you mean with: InsertAllObjects<T>(dictionary, expiration) ?

If you do this, how am I able to retrieve a particular list. Let's say I want to save a List<Person> that have a specific Lastname (they belong in one list).

If I store each element(Person) as a blob like you said, I indeed am able to retrieve each specific Person object. But if I do want the full list with the specific Lastname, how would I do this? Would it still be as efficient as querying it directly?

**Comment by paulcbetts** [comment]
If you need something like indices or structured querying, then a key-value store is not for you, you should use SQLite
