### ISSUE TITLE
Akavache crashes silently (apps just disappear) after data is cleared

### ISSUE THREAD

**Issue by khle** [akavache/Akavache#248]
On Android, go to settings and clear data.  Launch apps again(from device directly, NOT from Visual Studio).  Apps come up momentarily and just shut down silently.  I suspect that Akavache would need to check if backing SQLite is there.  If not, create and register blobs.db, userblobs.db and secret.db (I think).  Apps works fine after deployment and continue to work fine until the data is cleared in the settings.

**Comment by khle** [comment]
If the app has to ensure the db is present, then the document can specify the name and path of all the dbs that are required.

**Comment by flagbug** [comment]
What's the exception that occurs when the app crashes? Also I guess you're talking about Android?

**Comment by pragmaticlogic** [comment]
No exception.  As I wrote, app just shut down silently.

**Comment by paulcbetts** [comment]
logcat output?

**Comment by khle** [comment]
The issue only happens after the data and cache is cleared in the App Settings.  When one starts launching the app from VS IDE (or XS), the app is deployed to the device.  At this time, the bundled db is also deployed.  So no problem would happen here.  After the cache is cleared, the backing SQLite db is gone.  I suspect that at this time, any code that assumes the db is present might encounter some problem.  

So I think Akavache, as a library can handle this situation.  If the apps using Akavache are to handle, then the paths to the backing dbs would just need to be exposed. 

Anyway, the following is the logcat output that I captured:

monodroid-assembly  Could not load assembly 'MyApp.Droid' during startup registration
monodroid-assembly  This might be due to an invalid debug registration
monodroid-assembly  A common cause is to 'adb install' the app directly instead of from the IDE.

I wouldn't bother so much on this logcat output because they look kind of generic.  The issue can be fairly easy to reproduce by simply clearing the cache and launch the app again. 

Lastly, I don't think this is limited to Android.  But I will confirm on other platforms.

**Comment by flagbug** [comment]
Are you deploying the app in a Debug configuration with fast deployment via VS or XS? If that's the case, the problem isn't Akavache, but Xamarin, as it doesn't handle data/cache clears when fast deployment is enabled

**Comment by khle** [comment]
@flagbug Yes, you're totally right.  I had "fast deployment" enabled.  After seeing your response, I disabled "fast deployment" and repeat the same steps again.  The problem NO longer happens.  You're right that the problem is not with Akavache.  I will close this ticket if I could.
