### ISSUE TITLE
Does this work with SQLiteRaw 0.8.2

### ISSUE THREAD

**Issue by dhaligas** [akavache/Akavache#249]
@paulcbetts does this lib work with the latest SQLite Raw?

https://www.nuget.org/packages/SQLitePCL.raw_basic/

**Comment by paulcbetts** [comment]
No idea!

**Comment by dhaligas** [comment]
@paulcbetts looks like I am not the only one having an issue with this.

https://github.com/ericsink/SQLitePCL.raw/issues/48

**Comment by dhaligas** [comment]
@paulcbetts any plans to support it?

**Comment by paulcbetts** [comment]
@dhaligas My plan is to wait for the BCL to stop breaking msbuild files

**Comment by dhaligas** [comment]
@paulcbetts is there away around this before that happens?  I would like to have all of my packages up to date

**Comment by flagbug** [comment]
This seems to be fixed in SQLitePCL.raw, so I guess this issue can be closed

**Comment by dhaligas** [comment]
I have tried to update but akavache expects a certain version.  I get an error at runtime

**Comment by dhaligas** [comment]
When I rollback to SQLite 0.7.1 it works

**Comment by flagbug** [comment]
I don' think that Akavache has any version requirements
