### ISSUE TITLE
Remove Splat dependency

### ISSUE THREAD

**Issue by dominik-weber** [akavache/Akavache#250]
Hi,
I don't intend to use Splat, why is the dependency Akavache -> Splat and not Splat -> Akavache?

**Comment by paulcbetts** [comment]
Akavache uses Splat

**Comment by dominik-weber** [comment]
I can see that, but if you move the BitmapImageMixins class to Splat wouldn't it be possible to remove this dependency?

**Comment by paulcbetts** [comment]
Nope, Splat is used all over the place in Akavache
