### ISSUE TITLE
BlobCache.LocalMachine is NULL on Android but only in Release mode

### ISSUE THREAD

**Issue by DavePilks** [akavache/Akavache#251]
I have quite a frustrating issue when deploying my Xamarin.Forms Android App in release mode. The BlobCache.LocalMachine is null when in release mode but when I run the app in debug mode, there are no issues with it. 

I am not doing anything out of the ordinary with the library, do you have any idea why this would be happening?

**Comment by flagbug** [comment]
Try to exclude Akavache from the Xamarin Linker

**Comment by DavePilks** [comment]
@flagbug  I just tried this and it didnt work. The LocalMachine property is still null

**Comment by flagbug** [comment]
@DavePilks Did you add Akavache **and** Akavache.Sqlite3 to the linker exclusion? Also, do you have a project so we can reproduce this?

**Comment by DavePilks** [comment]
I added both and then even turned linking off. 

Ill try and recreate the problem in a sample app as I cannot add the current project for IP reasons

**Comment by flagbug** [comment]
@DavePilks Any update on this?

**Comment by flagbug** [comment]
If this is still an issue, lat me know and I'll reopen this
