### ISSUE TITLE
Windows 10 - NullReferenceException when compiling with .NET Native

### ISSUE THREAD

**Issue by mjracca** [akavache/Akavache#252]
I'm having the next exception when enabiling **Compile with .NET Native tool chain**, when I try to retrieve data from Akavache

```
An exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.dll but was not handled in user code
Additional information: Arg_NullReferenceException
If there is a handler for this exception, the program may be safely continued.
```

We need this to upload the app to the Store. Any clues?

**Comment by paulcbetts** [comment]
This is probably similar to iOS Linker issues, you probably need to include some dummy classes to trick the .NET Native linker to not strip something, though that error message isn't exactly illustrative :-/

**Comment by mjracca** [comment]
It looks like **Akavache.BlobCache.UserAccount** is null!

**Comment by paulcbetts** [comment]
@mjracca Yeah, I bet .NET Native kneecaps our automatic reflection-based set-up. You can just explicitly set it up yourself and assign the variable:

```cs
var fs = Locator.Current.GetService<IFilesystemProvider>();

fs.CreateRecursive(fs.GetDefaultRoamingCacheDirectory())
  .SubscribeOn(BlobCache.TaskpoolScheduler)
  .Wait();

BlobCache.UserAccount = new SQLitePersistentBlobCache(
  Path.Combine(fs.GetDefaultRoamingCacheDirectory(), "userblobs.db"), 
  BlobCache.TaskpoolScheduler);
```

**Comment by mjracca** [comment]
Ok, so adding that code generate tons of issues. So I created a new app, enable __Compile with .NET Native tool chain__ and just added akavache to the project, without adding any code at all.

When I run it I get this error:
![image](https://cloud.githubusercontent.com/assets/3976257/10678547/85d7504a-78e9-11e5-9a00-05665ba23482.png)

**Comment by paulcbetts** [comment]
@mjracca Can you attach WinDbg? that might be the easiest way to figure this out tbh. Open that EXE in WinDbg then type in the command window:

```
.symfix
.reload -f
g
```

Then when it blows up:

```
kn100
```

to get the stack

**Comment by mjracca** [comment]
Can't run Windows Universal apps in WinDdg:

```
This application can only run in the context of an AppContainer.
```

**Comment by paulcbetts** [comment]
:crying_cat_face:

**Comment by paulcbetts** [comment]
I mean, if I had to _guess_ why .NET Native is losing its mind, I'd guess that something about sqlite3.dll is being incorrectly distributed? Like missing VC++ Runtime maybe?

**Comment by mjracca** [comment]
"Good" news! So, we tried the solution in 5 different machines, and in 1 works (whaaaaaatt!!?). 

So your original answer fixes our issue with Akavache :smile: (5hrs of our life wasted)

Thanks!! :raised_hands:

**Comment by MattWhilden** [comment]
Hey there, I work on the .NET Native Compiler and Runtime team. Are you still hitting this issue?

**Comment by mjracca** [comment]
Yes! Thanks!

**Comment by MattWhilden** [comment]
If you do end up hitting it again (or similar oddities) please feel free to tag me. We're interesting in getting things like this chased down.
