### ISSUE TITLE
GetOrFetchLatest not retrieving latest

### ISSUE THREAD

**Issue by Mittchel** [akavache/Akavache#256]
Hi,

First of all; Akavache is awesome, thanks for the contribution :-)

There is just one thing I'm struggling with; I can't seem to retrieve the latest values with GetOrFetchLatest. It doesn't seem to go into the remote method and returns straight from cache. What am I doing wrong here?

```csharp
		public async Task<List<Article>> GetArticles(int currentPage)
		{
			var cache = BlobCache.LocalMachine;
			
			var cachedConference = BlobCache.LocalMachine.GetAndFetchLatest("articles", () => GetRemoteArticlesAsync(currentPage, 10, new List<string>(), new List<string>()), offset =>
			{
					return true;
			});

			var conference = await cachedConference.FirstOrDefaultAsync();	

			return conference;
		}
```

**Comment by paulcbetts** [comment]
Did this get resolved?

**Comment by Mittchel** [comment]
@paulcbetts I think so. I have to use the Subscribe right?

**Comment by paulcbetts** [comment]
@Mittchel Correct

**Comment by Mittchel** [comment]
@paulcbetts Thanks. I am using Xamarin Forms for my project. It has a ObservableCollection of <T>.

When I am using GetAndFetchLatest it will return 2 collections, thus will render 2 times. What's in your eyes the best way to tackle this?

I am really keen on hearing your opinion since your code is of high quality and you pay attention to clean code and architecture. 

Thanks!

**Comment by paulcbetts** [comment]
@Mittchel How to handle this depends on your app - sometimes it's appropriate to try and merge the two lists, sometimes it makes more sense to just stomp the old list with the new one, etc etc

**Comment by Mittchel** [comment]
@paulcbetts I was thinking the same. My idea was to use a Comparer and basically find the items that are different (updated).

Colleague of mine also wrote an ObservableCollection which doesn't fire for each item a property changed event. Thus I can do .Replace(item) and basically the view only updates that specific item; pretty neat. 

Just one last question..

I've got 2 projects: ViewModels and Services.

In my ViewModels I do something like: articleService.GetArticles(); The ViewModel also holds the Collection of type Articles which is returned by the Service call. (So it will be presented to the view).

 And in the Services project Akavache actually does the GetAndFetchLatest call. If I would like to use Subscribe this means I have to pass my ViewModel to the Service project so I can Replace items on the ObservableCollection.

I have a feeling that this is something bad to do, what do you think?

Thanks again :-)

**Comment by paulcbetts** [comment]
Return the Observable
