### ISSUE TITLE
Use SQLitePCL.raw instead of SQLitePCL.raw_basic

### ISSUE THREAD

**Issue by dominik-weber** [akavache/Akavache#257]
Currently the two packages have identical implementation, however the raw_basic will be discontinued and already lags behind in update releases.

**Comment by shiftkey** [comment]
Do you have a link to where they're talking about deprecating `raw_basic`?

**Comment by dominik-weber** [comment]
it says that right on the main page: https://github.com/ericsink/SQLitePCL.raw

There's another NuGet package called SQLitePCL.raw_basic. What is it??

That's the old package ID. With the 0.8.0 release, I transitioned to just 'SQLitePCL.raw' as the package ID (without the _basic suffix). Eventually I may stop publishing updates to the old ID. For now, the package gets published under both IDs and they are identical.

**Comment by shiftkey** [comment]
Okay, so we'd need to look at this when transitioning from 0.7.0 to 0.8.0.

Thanks for the heads up.

**Comment by paulcbetts** [comment]
:+1:

**Comment by ericsink** [comment]
I happened to see this issue linked on #291 , so at the risk of being redundant:

The task at hand now is to update to SQLitePCLRaw 1.0, which has changed package IDs yet again, but which will be following semver, so it should be the last time.  :-)
