### ISSUE TITLE
Database corrupting after I kill and restart the iOS app a few times in release build.

### ISSUE THREAD

**Issue by cristianomad** [akavache/Akavache#261]
My iOS app database data is vanishing after I kill the app process and restart it a few times (around 2 times). It happens only in release build. I'm already skipping linker for akavache and all its dependencies. 
`-linkskip=Akavache -linkskip=Akavache.Sqlite3 -linkskip=SQLitePCL.raw`. 

I'm using BlobCache.UserAccount. Here is my initialization code located in Main.cs file.

```c#
AppSettings.AkavacheDatabasePath = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.Personal), "../Library/akavache.db");

Akavache.BlobCache.ApplicationName = NSBundle.MainBundle.InfoDictionary ["CFBundleDisplayName"].ToString ();
Akavache.BlobCache.UserAccount = new Akavache.Sqlite3.SQLitePersistentBlobCache (AppSettings.AkavacheDatabasePath);
Akavache.BlobCache.EnsureInitialized ();
```

What could possibly be happening?

**Comment by paulcbetts** [comment]
Gotta be a little bit more verbose about what you mean by "Corrupting"

**Comment by cristianomad** [comment]
After I killed the app and open again a few times the cache data is completely erased.

**Comment by cristianomad** [comment]
Solved by saving the data again in the AppDelegate's WillTerminate method.
