### ISSUE TITLE
Synchronous not retrieving value whereas Async Await does 

### ISSUE THREAD

**Issue by JohnMcAvinue** [akavache/Akavache#263]
Hi,

Thanks for this great plugin!

I have spent most of the day trying to figure out why the following piece of code was always returning -1:

var value = -1;
            BlobCache.LocalMachine.GetObject<int>(key).Subscribe(x => value = x, ex => Console.WriteLine("No value found with key " + key));
            return value;

I have just tried it using the async await pattern and it worked:

try
            {
                return await BlobCache.LocalMachine.GetObject<int>(key);
            }
            catch (KeyNotFoundException ex)
            {
                Debug.WriteLine(ex.Message);
                return -1;
            }

Could this be a bug?

**Comment by flagbug** [comment]
The call to `Subscribe` isn't blocking, so you're firing off on another thread and your method immediately returns `-1`, whereas `await` waits on the `GetObject` call to complete

**Comment by JohnMcAvinue** [comment]
Thanks for the prompt reply. That makes sense now that you explain it.
