### ISSUE TITLE
Better documentation for when to choose BlobCache.UserAccount over BlobCache.LocalMachine

### ISSUE THREAD

**Issue by SimonSimCity** [akavache/Akavache#271]
The only documentation I can find for when to choose BlobCache.UserAccount over BlobCache.LocalMachine is:

> Store data that should be shared between different machines in BlobCache.UserAccount and store data that is throwaway or per-machine (such as images) in BlobCache.LocalMachine.

But what should I choose for mobile development? How is it handled f.e. for Android or iOS? What about Windows Phone 8.1 Universal Apps?

Can I f.e. trigger that the user-context has changed - that a different user is logging into the app? Is there a time you don't have a user-context (maybe related to #251)? Is there an easy way to clear the UserAccount storage if the user logs out?

**Comment by SimonSimCity** [comment]
After some research in code, I found an answer, suitable to my use-case:

Both mobile operation systems (iOS and Android) have native path directives for cache and persistent storage. The database for `BlobCache.UserAccount` is stored persistently, whereas `BlobCache.LocalMachine` is stored in a directory for cache-files. iOS will, as off it's own, start removing data from that storage when the storage gets to it's limits. Android remarks in the notes, that you yourself should care about cleaning that storage when it exceeds 1MB (http://developer.android.com/reference/android/content/Context.html#getCacheDir%28%29). I have not found a reference for Akavache, following that recommendation ...

In case you wonder about how the _secret_ values are stored - it's just in a subfolder of `BlobCache.UserAccount` :wink:

Could someone wrap this in a beautiful documentation and add it to the wiki?

Resources:
* https://github.com/akavache/Akavache/blob/9092dafcf540f0da0401a9defc6936326a507f34/Akavache/Android/AndroidFilesystemProvider.cs
* https://github.com/akavache/Akavache/blob/9092dafcf540f0da0401a9defc6936326a507f34/Akavache/MacFilesystemProvider.cs
* http://developer.android.com/reference/android/content/Context.html#openOrCreateDatabase%28java.lang.String,%20int,%20android.database.sqlite.SQLiteDatabase.CursorFactory%29

**Comment by ghuntley** [comment]
Can you please send in a documentation PR to `README.MD`?
