### ISSUE TITLE
Fresh Akavache Install Rendered Xamarin iOS app Dead.

### ISSUE THREAD

**Issue by jamsoft** [akavache/Akavache#273]
I've never used Akavache so on recommendation I installed it today to get it integrated.  I can no longer even debug the app.

The type initializer for 'Akavache.BlobCache' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Splat, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Splat, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'

When looking at the library references that have been added, it installed a referenced Splot v1.3.3, not 1.6.0.0 ...

I had to manually update Splat to 1.6.0 using NuGet.

**Comment by steveoh** [comment]
[duplicate](https://github.com/akavache/Akavache/issues/206)

**Comment by flagbug** [comment]
Closing as duplicate
