### ISSUE TITLE
BlobCache.LocalMachine and UserAccount always returning null

### ISSUE THREAD

**Issue by ryan-buckman** [akavache/Akavache#279]
After installing Akavache and then running my portable Xamarin Forms application as soon as I try and create either `BlobCache.LocalMachine` or `BlobCache.UserAccount` it throws a `ThreadAbortException` if I inspect `BlobCache` before setting it to LocalMachine or UserAccount it just says 'timed out'. I've installed Akavache to both my pcl, droid and iOS projects. After having a look round I can't see any obvious answer. Any ideas?

This causes the issue described above `var cache = BlobCache.LocalMachine;`

**Comment by jiujiu1123** [comment]
I think I had similar issues later solved by adding a dependency on the iOS project.

**Comment by jiujiu1123** [comment]
Have you attempted that method?

**Comment by ryan-buckman** [comment]
My iOS project references my main pcl if that's what you mean? If not could you explain how to add a dependency, thanks

**Comment by flagbug** [comment]
Does it throw that exception on botch iOS and Android?

**Comment by jiujiu1123** [comment]
I think you may need to add akavache package on ur iOS project,

**Comment by ryan-buckman** [comment]
yep akavache  has been added to my iOS project

**Comment by flagbug** [comment]
Can you create a reproduction example that we can just run?

**Comment by ryan-buckman** [comment]
Unfortunately not in it's current state due to the proprietary information - I've attached the stack trace if that's of any use 
[stacktrace.txt](https://github.com/akavache/Akavache/files/220837/stacktrace.txt)

**Comment by ryan-buckman** [comment]
So I fixed the issue, having the breakpoint at `var cache = BlobCache.LocalMachine;` was causing the time out and as a consequence the null reference. Removing the break point fixed all the issues.
