### ISSUE TITLE
Local machine cache expiration defaults

### ISSUE THREAD

**Issue by darylw** [akavache/Akavache#280]
Hi,

Quick question, is there a default expiration period on local machine cache? As I am using it for some settings data, nothing too important,  and for the most part it works, getting the data, setting it again, restart the app/phone, still works great. Love Akavache, it's essentially the core of my app, and works brilliantly.

However, starting my app up after an undetermined period of non usage, these settings appear to be lost - So I am wondering if when inserting an item into the local cache, and not specifying an expiration, that it will expire after say 24 hours? Or some pre-specified value. 

Or am I using it for a purpose for which it is not intended, and local cache always expires, and I should use secure cache for persistence instead?

Any info is appreciated.

Kind regards,
Daryl

**Comment by flagbug** [comment]
`LocalMachine` doesn't have an expiration time by default, it seems like the operating system you're on is purging some of your data. 

Apart from that, I'd use `BlobCache.UserAccount` for user data, `LocalMachine` is more for throw-away data, like image caches (But Akavache doesn't enforce that, or delete anything! It's just the directories in which the caches are created that differ)

**Comment by darylw** [comment]
@flagbug cheers for clarifying that. That's interesting, I'm using this on an Android device, so I wonder if there is anything there that would do that... Particularly on a Samsung with all the bloatware installed on it. Don't suppose you know of anything on any device that would do that? Perhaps a Smart cleanup tool or something similar? (Not that I use it, just looking for possibilities)

I started with a mix of local and user, but ended up moving it all around. Ok that's good to know about the directories, thank you for that.

**Comment by darylw** [comment]
Closed - issue resolved due to it being a device based issue
