### ISSUE TITLE
Can't install Akavache anymore

### ISSUE THREAD

**Issue by Mittchel** [akavache/Akavache#281]
Hi,

I've been using Akavache a lot, but suddently I'm unable to install Akavache anymore in my Xamarin.Forms project. Actually, in any project.. 

Getting the following:

Install failed. Rolling back...
Package 'akavache.sqlite3.4.1.2 : akavache.core [4.1.2, 4.1.2], SQLitePCL.raw_basic [0.7.0, )' does not exist in project 'IskaDemo'

Any idea's on this? Even if I add the raw package manually it keeps failing on me. Hope someone is able to help me out, since I'm preparing a demo to show Akavache..

Has this anything to do with the Alpha Xamarin Studio version?

**Comment by ghuntley** [comment]
Resolved at https://github.com/akavache/Akavache/pull/291#issuecomment-253601110 please test using the packages on myget.
