### ISSUE TITLE
Index the TypeName and Expiration

### ISSUE THREAD

**Issue by flagbug** [akavache/Akavache#285]
I'm seeing multiple WHERE clauses on the TypeName and Expiration fields of the Sqlite CacheElement [here](https://github.com/akavache/Akavache/blob/5e94aed82c6caa9e006a0232ded74d3d00bfe9f2/Akavache.Sqlite3/Operations.cs#L119), [here](https://github.com/akavache/Akavache/blob/5e94aed82c6caa9e006a0232ded74d3d00bfe9f2/Akavache.Sqlite3/Operations.cs#L202), [here](https://github.com/akavache/Akavache/blob/5e94aed82c6caa9e006a0232ded74d3d00bfe9f2/Akavache.Sqlite3/Operations.cs#L326) and [here](https://github.com/akavache/Akavache/blob/5e94aed82c6caa9e006a0232ded74d3d00bfe9f2/Akavache.Sqlite3/Operations.cs#L454), so it would probably make sense to create a database index over them.

This may also be the underlying issue in #284

**Comment by mms-** [comment]
Lack of index could do it. Realm.io may be a good idea.

**Comment by mms-** [comment]
Yes this is the reason for #284 
Just as a test I removed where clause [here](https://github.com/akavache/Akavache/blob/master/Akavache.Sqlite3/Operations.cs#L454) (also removed line 475) and it is nearly 100 times faster.

Hard to make this change and push a new NuGet? Or should I do it on my own fork?

**Comment by flagbug** [comment]
@mms- I don't know when a new version will be out, it's probably best, if you use your own fork right now!

**Comment by mms-** [comment]
Is the NuGet far behind master?

**Comment by flagbug** [comment]
It's not much: https://github.com/akavache/Akavache/compare/4.1.2...master
