### ISSUE TITLE
How to get an expired object?

### ISSUE THREAD

**Issue by letsar** [akavache/Akavache#301]
How can I get a value from akavache even if the value is expired?
If I use the following code I get a `KeyNotFoundException` and I didn't find a way to specify that I don't care whether the value is expired or not:

``` C#
blobCache.InsertObject<string>("test", "value", DateTimeOffset.UtcNow).Wait();
string expiredValue = blobCache..GetObject<string>("test").Wait();
```

I could use `GetAndFetchLatest`but in case my app is offline, I rather get an expired value than nothing at all.
I saw in the code that in the case of the `SqlitePersistentBlobCache`, this condition prevents the value to be returned is it's expired:

``` C#
if (now.UtcTicks <= ce.Expiration.Ticks) result.Add(ce);
```

**Comment by flagbug** [comment]
I don't think there's currently a way to do that, sorry

**Comment by letsar** [comment]
Ok, thanks for the answer.
We had to store the expiration value in our object and manage ourself whether we should fetch the value from the web service or keep the cached value.
Maybe there is a better solution.

**Comment by shiftkey** [comment]
Yeah, I don't think this is something Akavache has been designed for. Closing this out.
