### ISSUE TITLE
Akavache Meeting Minutes - 8th of July 2016 

### ISSUE THREAD

**Issue by ghuntley** [akavache/Akavache#304]
# In attendance
- Paul Betts
- Brendan Forster
- Kent Boogart
- Oren Novotny
- Geoffrey Huntley
- Dennis Daume
- Michael Stonis
# With Apologies
- Paul Betts, as we bait and switched him with the promise of a social occasion with beer.
# The Plan
## Reactive Extensions
- We will be upgrading to the latest version of Reactive Extensions in RxUI and all sister projects.
- Upgrading to latest version of Reactive Extensions is a breaking change and merits bumping the major.
  - Strong naming key is different and this will affect WPF applications that are strongly signed.
  - Using the new bits means migrating the project to netstandard.
## SemVer
- Oren proposed that we adopt the .NET SemVer guidelines and there were no objections. We will move forward and adopt https://docs.microsoft.com/en-us/dotnet/articles/core/versions/index#semantic-versioning for ReactiveUI and all sister projects. - https://github.com/reactiveui/ReactiveUI/issues/1134
## Akavache
- Upgrade SQLitePclRaw to resolve the Android N sqlite incompatibility. - https://github.com/akavache/Akavache/issues/306
- Upgrade to the new version of Rx - https://github.com/akavache/Akavache/issues/307
- Netstandard will be adopted - https://github.com/akavache/Akavache/issues/308
- The major number will be bumped in the next release (needed because of netstandard and new rxbits)
- The continuous integration pipeline will be lifted from ReactiveUI and brought across to the Akavache project - https://github.com/akavache/Akavache/issues/305

**Comment by flagbug** [comment]
I probably have time for some of these at the end of next week :+1:
