### ISSUE TITLE
Akavache SQLitePCL.ISQLite3Provider::sqlite3_enable_shared_cache could not be resolved

### ISSUE THREAD

**Issue by Karuna30** [akavache/Akavache#314]
I am trying to use Akavache in my Xamarin Forms PCL Project. I already have implemented ISQLite dependency for both Android and IOS, and that works fine.

However as soon as I added Akavache Nuget in PCL, IOS and Android Project I keep getting this error:

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: 
Error executing task LinkAssemblies: error XA2006: Reference to metadata item 'System.Int32 SQLitePCL.ISQLite3Provider::sqlite3_enable_shared_cache(System.Int32)'
(defined in 'SQLitePCLPlugin_esqlite3, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') 
from 'SQLitePCLPlugin_esqlite3, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' 
could not be resolved.
```

Running 
Xamarin Studio : 6.1 
Akavache 4.1.2

Would really appreciate any pointers to resolve this!

**Comment by ericsink** [comment]
This will probably depend on transitioning Akavache to the 1.0 release of SQLitePCLRaw.  #306

**Comment by Karuna30** [comment]
I am not 100% sure I understand you. Do I need to wait for 5.0 or is there a workaround for now?
I already have sqlite-net-pcl and its dependencies already in my project, and I guess it is conflicting when I try to add SQLitePCLRaw.bundle_e_sqlite3.1.0.1 and use SQLitePCL.Batteries.Init();

**Comment by ericsink** [comment]
I'm not 100% sure I know exactly what is causing this problem, so I can't be 100% sure about diagnosis and workaround.  :-)

You definitely can't just add SQLitePCLRaw 1.0 stuff to a project using Akavache 4.

I suspect you will need to wait for Akavache 5.

That said, my first guess at a workaround would be to change the properties on your Xamarin.Android project to not "link".

**Comment by Karuna30** [comment]
@ericsink Do we have an update on Akavache 5 Relese day, I am really looking forward to integrate it in my app?

**Comment by ericsink** [comment]
There is some motion on this, see #317

**Comment by ghuntley** [comment]
Resolved at https://github.com/akavache/Akavache/pull/291#issuecomment-253601110 please test using the packages on myget.
