### ISSUE TITLE
Is there any limit to the size of blob I can put into Akavache?

### ISSUE THREAD

**Issue by redwards1966** [akavache/Akavache#324]
I've been working on caching some restful api's in a Xamarin mobile app that I have inherited. The previous dev was returning a `ServiceResponse<List<ArticleCategoryInfo>` object where `ServiceResponse` basically had the full response object like so, plus some other treats:

	public class ServiceResponse<T>
	{
		public HttpResponseMessage Response { get; set; }
		public bool Authorized { get; set; }
		public string Message { get; set; }
		public T Result { get; set; }
	}

I was trying to cache the whole thing just because I didn't want to have to refactor the entire app off the start to see how caching would affect the speed but I found that when I cached it, it was always hitting the restful endpoint instead of getting from the cache even though it wasn't expired. When I switched to just caching the `Result` which is all I really needed Akavache started behaving as I figured it should.

**Comment by shiftkey** [comment]
@redwards1966 maybe there's some issues with deserializing a `HttpResponseMessage`? You can check the object has been stored successfully by enumerating the keys stored with `.GetAllKeys()` - that'd be an easy way to sanity check before digging too deep...

**Comment by ghuntley** [comment]
What @shiftkey said @redwards1966.  Does `HttpResponseMessage` convert to JSON okay? (i.e. no circular object references). Akavache doesn't really have a size limitation - if your device has memory to do the operation then it'll do it. There are no streaming API(s) - the entire structure must be loaded in full in and out of memory; we would consider a discussion/pull-request (after API design discussion) about implementing a streaming API.

**Comment by ghuntley** [comment]
Whack a `[IgnoreDataMemberAttribute]` on your `HttpResponseMessage` in the base class and you'll be back to shipping in 5 minutes.

**Comment by redwards1966** [comment]
Thanks gentlemen, I'll give these suggestions a try.
