### ISSUE TITLE
SQLiteAsyncConnection accessible in Akavache 5

### ISSUE THREAD

**Issue by logikonline** [akavache/Akavache#330]
Thank you for updating the library but we previously accessed the SQLiteAsyncConnection from Akavache.Sqlite3.Internal which we see is no longer accessible. This was vital for us to provide the seamless use of the library.

Reading the documentation from Android - is there some steps we can do to allow us to use this object? Can Akavache expose this or can you provide us with the steps necessary to continue using this?

Any assistance is greatly appreciated.

**Comment by flagbug** [comment]
`SQLiteAsyncConnection` was in the `Akavache.Internal` namespace and shouldn't be used from the outside.

Also it was just copied from some version of the `sqlite-net` project, so you can still get it from there and copy it into your own project.
