### ISSUE TITLE
Akavache bug when used with Azure Mobile Services Offline sync in Xamarin Forms app

### ISSUE THREAD

**Issue by fenix2222** [akavache/Akavache#332]
I am using Azure Mobile services for mobile offline sync in Xamarin Forms app. I am also trying to use Akavache to store user specific settings and cache that is only to be saved on that device and doesn't need to be synced to cloud. 

If used separately, my azure client works well, I get data synced no problems. Same for Akavache, when used without azure mobile sync, I can easily save and retrieve my local data. However, there is an issue when used together. As soon as I make a call to any azure client sync functions (i.e. pullasync or pushasync) and then try to use Akavache later in the app, it fails silently and application crashes. I am getting SIGSEGV error in my output with no stacktrace. 

I have a feeling it is somehow related to Azure Client and Akavache using same static SQLite connection object or something similar. Any pointers here?

**Comment by ericsink** [comment]
Hmmm.

Conjecture: Both of these libs are trying to call Batteries.Init().  If they both make their call separately, at the beginning of the app's run, everything should be fine. But maybe if one of them is trying to call Init() later, and it is happening while the other one is actively using SQLite?  That might be a problem.

**Comment by fenix2222** [comment]
@ericsink How do I manually call Batteries.Init() for Akavache?

**Comment by ericsink** [comment]
Just try doing any simple Akavache operation to force the library to initialize itself.

**Comment by fenix2222** [comment]
But I am doing this, i.e. Akavache is already used in the app leading to the screen which uses Azure Mobile Sync. So I am already saving and reading stuff from Azkavache prior to calling Azure Sync. Then once Azure sync is done (and it is also successful) and subsequent calls to Akavache fail, not matter where they are in the app (i.e. on a current page or later in some other screen). The problem is that a fatal crash which a cannot catch and it doesn't give me any useful error details.

**Comment by ericsink** [comment]
Well I'm just guessing at what might be happening.

Is the Azure library also doing something early that would force it to initialize?

If both libs are initialized early, then my guess is probably wrong.

**Comment by fenix2222** [comment]
Azure sync is initialized later in the code. I will try to init it earlier and see if it makes any difference

**Comment by fenix2222** [comment]
Ok tried this now:

Initialized azure client first -SUCCESS
Used Akavache (get/insert) - SUCCESS
Try to use sync - FAILURE AGAIN

So it is now reversed.

Here is all the output I get:
critical:   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) [0x00031] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:893
2016-12-07 19:49:25.354 BrixnMobileUIiOS[52036:14315387] critical:   at System.Threading.ThreadHelper.ThreadStart (object) [0x00012] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/thread.cs:87
2016-12-07 19:49:25.354 BrixnMobileUIiOS[52036:14315387] critical:   at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <IL 0x00053, 0x00310>
2016-12-07 19:49:25.354 BrixnMobileUIiOS[52036:14315387] critical: 
Native stacktrace:

2016-12-07 19:49:25.354 [52036:14315387] critical: 
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

**Comment by ericsink** [comment]
Okay, can you try something and let me know if it helps?

Update the SQLitePCLRaw.Core nuget pkg to this prerelease build:

https://www.nuget.org/packages/SQLitePCLRaw.core/1.1.2-pre20161207051304

In your app initialization, before anything happens with Akavache or the Azure library, add these two lines:

    SQLitePCL.Batteries.Init();
    SQLitePCL.raw.FreezeProvider();

**Comment by fenix2222** [comment]
Thanks @ericsink. I will have to try it tomorrow

**Comment by ericsink** [comment]
Any update on this?

**Comment by fenix2222** [comment]
No, not yet. Trying to find time to test.

**Comment by fenix2222** [comment]
I have updated to pre-release version and now I am getting conflicts when trying to add 
`SQLitePCL.Batteries.Init();
SQLitePCL.raw.FreezeProvider();`

I get problems as I have libraries SQLitePCLRaw.bundle_e_sqlite3 and SQLLitePCLRaw.bundle_green  both having these functions. I cannot remove either of them as "e_sqlite" one is referenced by Akavache and "green" on e is referenced by Azure Mobile Client nuget. What is the difference between those? Maybe this is the cause of my problems?

**Comment by fenix2222** [comment]
@ericsink I figured out how to resolve e_sqlite3 and green bundles so there is no conflict. I just used dll aliases. Your prerelease fixed carsh issue now!!! It seems to work. I tried different combinations and all seem to work without any crashes now. When do you think we can get stable release?

**Comment by ericsink** [comment]
> When do you think we can get stable release?

Probably soon.  I just need to think and make sure that the FreezeProvider() API is the way I want to support it forever.  :-)

**Comment by ericsink** [comment]
self.nag()

**Comment by ericsink** [comment]
SQLitePCL.raw 1.1.2 has been pushed to nuget.org.

The docs on FreezeProvider() are here:

https://github.com/ericsink/SQLitePCL.raw/wiki/Using-multiple-libraries-that-use-SQLitePCL.raw

**Comment by arthurrump** [comment]
@fenix2222 
> I figured out how to resolve e_sqlite3 and green bundles so there is no conflict.

I'm having a similar problem with referencing both e_sqlite3 and green, but I haven't been able to solve the conflict yet. Could you please provide some more details on how you fixed it? Thanks!
