### ISSUE TITLE
Is akavache thread safe on iOS?

### ISSUE THREAD

**Issue by gjorgji88** [akavache/Akavache#335]
Is akavache thread safe on iOS?

When using this component on iOS, the app crashes in unexpected moments. 

I can see that when establishing SQLiteConnection the FullMutex flag is not used. 
As far as i know SQLite.raw is not thread safe on iOS by default. Is there some special setting for using akavache on iOS or this needs to be implemented on top of akavache usage.

**Comment by ericsink** [comment]
Which versions are you using?  Akavache v5 should be fine as far as thread safety on all platforms.

**Comment by gjorgji88** [comment]
Just upgraded to version 5.0.0. Newest version is not tested yet I will notify if problem still persists.

**Comment by ericsink** [comment]
I think the problem will go away with the upgrade to v5.  If you have further difficulties, feel free to reopen this issue and post more details.

**Comment by gjorgji88** [comment]
Yeah it seems like the issue is resolved after upgrade. App runs smooth now on iOS.
