### ISSUE TITLE
iOS physical device *only* crash on .GetObject

### ISSUE THREAD

**Issue by tlhintoq** [akavache/Akavache#336]
VS2015u3 - MacMini - iPad3 iOS 10.2 (all latest everything as of 27dec2016)

Getting a value with this code works fine on droid project, and even remoted iOS emulator, but crashes the app on a physical device.  Very odd.  Doesn't even go to the `Catch` block: Exits the app IMMEDIATELY with very little help/info to go on.
Change from `.UserAccount` to `.LocalMachine` makes no difference.

```
            try
            {
                BlobCache.UserAccount.GetObject<int>("SequenceNumber")
                    .Subscribe(x => SequenceNumber = x, ex => SequenceNumber = 1);
                logger?.Information("New seq. number> {seqno}", SequenceNumber.ToString());
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"GET Error {ex.Message}");
            }
```

**Comment by ericsink** [comment]
Hmm.  Anything in the application output?  Or on the iPad's console?  It's probably a crash at the native code level, so there oughta be some error messages output somewhere.

**Comment by tlhintoq** [comment]
0500hrs Thanks for the fast response.  Soon as I get to the office I'll re-run.  "iPad's console"?? That's a new one on me.  Can you elaborate on "iPad's console"?

**Comment by tlhintoq** [comment]
Thanks for mention of "iPad Console" - with a little Googling I found [iOS Console](http://lemonjar.com/iosconsole/).  That lead me to see that the crash was right after a sound player object was disposed.

Here's why that looked (erroneously) like Akavache:
Akavache would get the persisted values which included sound settings like beeptone and volume.
Those got set, resulting in the tone being played at the new value.
The player then got disposed.
The devices Springboard then thru a fit.
All of this happening in separate threads.

In the time it took to F10 from one line to the next, the sound was played and player disposed and app crashes.  From a Visual Studio perspective it looks like the crash took place from trying to get the persisted value because it never makes it to the very next line.

I owe you an applogy for claiming it was your code.  I'm sorry.
And thank you again for pointing me toward the concept of a console viewer for the iPad!

Please consider this resolved.

**Comment by ericsink** [comment]
No worries.

I meant to reply again with more info, but it looks like you figured everything out.  :-)
