### ISSUE TITLE
A typo in README.md

### ISSUE THREAD

**Issue by sqc1999** [akavache/Akavache#340]
In the [Getting started](https://github.com/akavache/akavache#getting-started) section of `README.md`, there is an `Ater` seems should be `After`.

**Comment by ghuntley** [comment]
Can you send in a pull request please?

**Comment by sqc1999** [comment]
@ghuntley PR created, sorry for the delay.

**Comment by ghuntley** [comment]
No need to apologize; thanks for being a contributor.
