### ISSUE TITLE
GetObject throws exception instead of returning null when key is not present in cache

### ISSUE THREAD

**Issue by rupreetg** [akavache/Akavache#344]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/Akavache . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Feature Request: Right now, GetObject throws an exception instead of returning null in case the key is not present. Probably there must be a rational behind this design but from usability, I would love to get null returned instead of exception. If you can explain the reasoning behind the design, that'll be great and if we agree we should do this, I can send a pull request. 

**What is the current behavior?**
Currently, an exception is thrown back if Key is not present. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Not a bug

**What is the expected behavior?**
Not a bug

**What is the motivation / use case for changing the behavior?**
Exceptions should be implemented when we really have an unexpected behavior. In this case, it is expected that cache might not have the data so we should handle it differently. 

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**
I haven't tried before but I assume this is a design decision rather than an issue. 

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by shiftkey** [comment]
> Probably there must be a rational behind this design but from usability, I would love to get null returned instead of exception. If you can explain the reasoning behind the design, that'll be great and if we agree we should do this, I can send a pull request.

This is something that's been a part of Akavache's design from the beginning (I can trace it back to https://github.com/akavache/Akavache/pull/16 where SQLite was first added), so changing this behaviour I think is A Big Deal™.

I can't point to any specific design decisions, but I suspect we can't change the behaviour as **null cannot be used to represent a value type**. 

I have a couple of questions before we go any further:

- how are you using Akavache (is it with Observables or Tasks?) This might seem like a silly question, but it'll help me provide better context.

 - if you are worried about a key not being found, are you enumerating the `IBlobCache. GetAllKeys()` collection first, to ensure your key exists?

**Comment by rupreetg** [comment]
We just got started with Akavache about 2 weeks back and we are using it using Tasks. Here is the sample code for storing AuthToken

```
                try
                {
                    _authResult = await BlobCache.UserAccount.GetObject<AuthenticationResult>(Constants.DB_userAuthKey);
                }
                catch (Exception)
                { 
                    // Couldn't find in cache 
                }
```

I am not yet enumerating the collection though I can try doing that. 

Yes, changing the existing method will be a big change and it might be a breaking change for existing apps, I was thinking more on the lines of implementing a new method (TryGetObject?) and calling GetObject internally.

What are your thoughts about if we should avoid throwing exception, what and how do we do is what we can discuss.

**Comment by ghuntley** [comment]
I'm _really_ against changing this behaviour. This type of change would create a rift in the community.

**Comment by shiftkey** [comment]
@ghuntley agreed. I think this can be addressed with some general advice about API usage.

**Comment by shiftkey** [comment]
For now, here's a little introduction to using `GetAllKeys` with async/await. I'll come back to the story with observables in a follow-up:

```csharp
using Akavache;
using System;
using System.Linq;
using System.Reactive.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            RunTask().Wait();

            Console.ReadLine();
        }

        static async Task RunTask()
        {
            var key = "1234";

            var cache = new InMemoryBlobCache();

            // comment out this line to test both paths
            await cache.InsertObject(key, 5678);

            var keys = await cache.GetAllKeys();
            if (keys.Contains(key))
            {
                var result = await cache.GetObject<int>(key);
                Console.WriteLine($"Found value: {result}");
            }
            else
            {
                Console.WriteLine($"Could not find key");
            }
        } 
    }
}
```

**Comment by shiftkey** [comment]
Building upon that last snippet, here's a quick introduction into `IObservable<T>` and `IObserver<T>` and why we can't return `null`. It's not intended to be runnable:

```csharp
using System;
using System.Collections.Generic;
using System.Reactive.Subjects;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // a Subject implements IObservable<T> and IObserver<T>,
            // it's a nice way to programmatically play with observables 
            var subject = new Subject<int>();

            // this is how we create a subscription, which is basically
            // a callback that lets us handle data from the observable
            var subscription = subject.Subscribe(
                value => Console.WriteLine($"OnNext ${value}"),
                ex => Console.WriteLine($"OnError ${ex}"),
                () => Console.WriteLine($"OnCompleted"));

            // it's expected that 0 or more values are sent to the observable
            // and then it will either signal completion or error.
            // after this, it's considered terminated
       
            // this is how pass a value to the subscriber from the Observer
            subject.OnNext(5678);

            // and this is how we signal to the subscriber no more values will be sent
            subject.OnCompleted();

            // to signal an error the subscriber that needs to be handled
            // this is an error in the  System.Collections.Generic namespace
            // and it makes sense for collections like our cache
            subject.OnError(new KeyNotFoundException());

            // if you're done with the subscription, you should dispose of it
            subscription.Dispose();

            // however because IObservable<T> and IObserver<T> can be created
            // with reference types or value types, null cannot be used as a 
            // value to be returned because null cannot be used for value types
            subject.OnNext(null); //  Argument 1: cannot convert from '<null>' to 'int'

            // Akavache does not care what you decide to serialize, and I suspect
            // throwing an error for the "key not found" scenario is consistent
            // with how callers would expect collections to behave in .NET
            // (even though Akavache doesn't implement these interfaces explicitly)
        }
    }
}
```

**Comment by shiftkey** [comment]
And thirdly, here's how I'd do all this without Tasks:

```csharp
using Akavache;
using System;
using System.Linq;
using System.Reactive.Linq;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var key = "1234";

            var cache = new InMemoryBlobCache();

            // comment out this line to test both paths
            cache.InsertObject(key, 5678).Wait();

            RunObservable(cache, key);

            Console.ReadLine();
        }

        static IDisposable RunObservable(IBlobCache cache, string key)
        {
            return GetObjectSafe<int>(cache, key)
                .Subscribe(
                    result => Console.WriteLine($"Found value: {result}"),
                    () => Console.WriteLine("Completed"));
        }

        // I've named this method in this way because I didn't want to surface a null
        // when you don't have the key (trust me, the code looks awful) and I wanted
        // to show a bit more about Observables
        static IObservable<T> GetObjectSafe<T>(IBlobCache cache, string key)
        {
            // from the original IObservable<string> we can use LINQ-like operators
            // to transform the results and build up more complex sequences
            return cache.GetAllKeys()
                // Select() is a way to map the value received to a different type
                // other programming languages call this a "map"
                // In this case, we're mapping IEnumerable<string> to a boolean
                // this then flows to the subsequent method
                .Select(keys => keys.Contains(key))
                // SelectMany is a way to flatten Observable<Observable<T>> to Observable<T>
                // that probably sounds scary, but all we're doing here is, based on
                // whether we found the key, to lookup the value or return an empty observable.
                // to the caller this just looks like an Observable<T>, which makes their lives easier 
                .SelectMany(found => found ? cache.GetObject<T>(key) : Observable.Empty<T>());
        }
    }
}
```

**Comment by shiftkey** [comment]
I'll let @rupreetg have a read of this and ask other questions before I close this out, but I'm 👎 to changing this behaviour.

**Comment by rupreetg** [comment]
Thank you @shiftkey and @ghuntley for the explanation. I haven't worked with Observables before so probably I need to look into and understand it better. 

I've seen all 3 samples you shared, they makes sense. I also looked into the implementation of GetAllKeys and tried to understand what we do under the hood. I don't think it's bad from performance as we're doing all in memory, right? 

I'm Ok to close this for now :)

**Comment by shiftkey** [comment]
> I don't think it's bad from performance as we're doing all in memory, right?

The SQLite stuff that Akavache is using is designed to be fast. I wouldn't worry about it unless you're seeing specific throughput issues.
