### ISSUE TITLE
Caching objects with private setters?

### ISSUE THREAD

**Issue by ZoranBebic** [akavache/Akavache#346]
Hi,

I recently stumbled upon this "issue" trying to cache a simple object that had few private setters. Now I understand deserialization uses default constructor and then reinitializes an object through public properties.

Question here is if deserialization should abide by private setter rules? For the purists who design their classes with private setters for whatever reason that applies at compiler level. IMO there is no need for deseiralization to not set private setters and even if one takes a look at DataContractSerializer there is support for such behavior through SerializeReadOnlyTypes.

Can we expect deserializing through private properties behavior in Akavache?

**Comment by ZoranBebic** [comment]
Good enough I guess just need to remember next time I need to write own resolver :)

**Comment by shiftkey** [comment]
@ZoranBebic :thumbsup:
