### ISSUE TITLE
.NET Standard Support

### ISSUE THREAD

**Issue by johnamcruz** [akavache/Akavache#354]
Are you guys planning to support .NET standard 1.3?

**Comment by shiftkey** [comment]
We're not targeting it explicitly (at some point we should go back and refresh to align with .NET Standard stuff), but `net45` is supported - and that seems to line up with the [supported platforms](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3.md).

Could you elaborate on what you mean by "support"? What are you trying to do? And does something not work currently?

**Comment by johnamcruz** [comment]
Actually, its not akavache thats the problem. @shiftkey 

Package Rx-Interfaces 2.2.5 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package Rx-Interfaces 2.2.5 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-net40+sl5+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile136)
  - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32)
  - sl5 (Silverlight,Version=v5.0)
  - win8 (Windows,Version=v8.0)
  - wp71 (WindowsPhone,Version=v7.1)
  - wp8 (WindowsPhone,Version=v8.0)
One or more packages are incompatible with .NETStandard,Version=v1.3.

**Comment by shiftkey** [comment]
We're tracking upgrading to Rx v3 (which should address this) over in https://github.com/akavache/Akavache/issues/307.
