### ISSUE TITLE
CS0012 error

### ISSUE THREAD

**Issue by Nathan187** [akavache/Akavache#361]
trying to follow the documentation of this.  always getting an saying.  it could be a basic hello world project and this error always happens...

Error CS0012: The type 'Unit' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. (CS0012) (

**Comment by Nathan187** [comment]
no longer an issue, sorry

**Comment by Bartmax** [comment]
mind to tell how you fixed it ?

**Comment by dsplank** [comment]
@Bartmax I ran into the same issue and I was able to resolve it by adding the nuget package System.Reactive.Core to the project. You can install the latest version and not the specific version that it references in the error message.

**Comment by vector-man** [comment]
Still broken for me. Using latest ReactiveUI with WinForms.

**Comment by vector-man** [comment]
Nevermind ... Had old Rx packages. I see they were renamed. It was causing a conflict when I updated my packages.
