### ISSUE TITLE
InvalidateObject<T>(Key) not working

### ISSUE THREAD

**Issue by renzska** [akavache/Akavache#362]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/Akavache . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

When using using InsertObject<T>(key), then later trying to InvalidateObject<T>(key), it does not clear the item from the cache.

InvalidateAllObjects<T> works and removes all of that type, but the InvalidateObject<T>(key) does not work.

(Update: Problem exists with Encryption Provider and without)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

INSERT:
```
await BlobCache.Secure.InsertObject<Encounter>($"encounter{encounter.EncounterId} ", result);
```

DELETE:
```
var asdf = await BlobCache.Secure.InvalidateObject<Encounter>($"encounter{encounter.EncounterId}");

//check existing keys:
 BlobCache.Secure?.GetAllKeys()?.Subscribe(async keys =>
                   {
                       foreach (var key in keys)
                       {
                           Debug.WriteLine($"[Key] {key}");
                       }
                   }, ex =>
                   {
                       Debug.WriteLine("SUBSCRIBE ERROR:" + ex.Message);
                   });
```

Logs:

```
[DeleteEncounter] encounter54
[Key] orgEncounterCategories
[Key] dataversions
[Key] encounter54 
```

**What is the expected behavior?**

The item keyed should be removed.

**What is the motivation / use case for changing the behavior?**

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**

5.0.0

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by renzska** [comment]
Bah, there was space in my insert key... Resolved.

**Comment by renzska** [comment]
await BlobCache.Secure.InsertObject<Encounter>($"encounter{encounter.EncounterId} ", result);

should be

await BlobCache.Secure.InsertObject<Encounter>($"encounter{encounter.EncounterId}", result);

**Comment by EmilAlipiev** [comment]
> InsertObject

what is wrong with having space? can Key not have space anywhere in the key?
