### ISSUE TITLE
App Crash at startup in iOS Release

### ISSUE THREAD

**Issue by CR4567** [akavache/Akavache#363]
Hi,
I'm working on a app crash for some days now. 
It's an XF PCL project on .NET Profile 7, using Akavache 5.0 and was working now for several months.
The problem occurs only on iOS when the app is opening in the loading screen and only for device releases.

Since the log output wasn't very helpful to me ([stacktrace.txt](https://github.com/akavache/Akavache/files/1130879/stacktrace.txt)), I tried to debug it using Console outputs. I could narrow it down the initialization of Akavache. That's the reason why I'm writing here, hoping that anyone has a solution or at least an idea.

I'm calling Akvache in the shared code at startup:
```
public EasierLifeApp()
{
	InitCache();			
	InitializeComponent ();
}
```

```
public void InitCache() { 
	BlobCache.ApplicationName = "EasierLife";
	BlobCache.EnsureInitialized();
	_cache = BlobCache.LocalMachine;
}
```

For me, it looks like the app is not able to open the sql file. But don't see a reason why that could be.

**Comment by mattycare** [comment]
I had this issue when I was trying to use BlobCache.LocalMachine on a Xamarin.Android application I was working on.
I found no solution to the problem, and just bit the bullet in the end, using BlobCache.UserAccount instead. If anyone has a solution other than this, I'd be interested to know what it is :)

**Comment by CR4567** [comment]
thanks for the tip. I tried changing this options but didn't make a difference. 
Furthermore, I figured out that even the first call on BlobCache.ApplicationName triggers the error. 
So I think it could be related to the initialization process. Still trying to dive deeper into that code.

**Comment by CR4567** [comment]
ok I fixed this stupid error....
Finally it was a problem with one of the Rx Plugins... I reinstalled all of them (same version) and now it's working again... It looks like there was kind of a corruption in one the plugins. :-(
