### ISSUE TITLE
Set TargetPlatformMinVer

### ISSUE THREAD

**Issue by onovotny** [akavache/Akavache#370]
In this you have the TargetPlatformVersion, but you also probably want to specify the TargetPlatformMinVersion. It defaults to 10.0.10240.0...and that version isn't even in support anymore :)

https://github.com/akavache/Akavache/blob/883b2ae8ac492866b1a72113c833269b7a6845e8/src/Directory.build.targets#L10

**Comment by PureWeen** [comment]
https://github.com/akavache/Akavache/pull/376
