### ISSUE TITLE
Handle self-signed https url

### ISSUE THREAD

**Issue by Nevyn75** [akavache/Akavache#388]
Hi.

I'm using my own self-signed web server to develop.
In this case I noticed that calling :
`BlobCache.UserAccount.DownloadUrl(...)` passing my https url, results in an execption with message:
> "TrustFailure (The authentication or decryption has failed.)"

Is there a way to disable checks on certificates?

Thank you for support.

**Comment by PureWeen** [comment]
If I remember correctly you do that by setting the following global static 

System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

Which I'm pretty sure has to be set inside each platform project

**Comment by ghuntley** [comment]
Howdy @Nevyn75. Alright so the best (and only) way to do this is to either get a valid certificate or add your cert as trusted on your computer or disable callbacks for each platform. We won't be adding any overrides to disable SSL within the Akavache public API.
