### ISSUE TITLE
(UWP) Payload contains two or more files with the same destination path 'SQLitePCLRaw.batteries_v2.dll'. 

### ISSUE THREAD

**Issue by mesta1** [akavache/Akavache#389]
I'm trying to use Akavache with UWP, but I can't get it working. I'm already using Sqlite-net-pcl and I would like to use both.

What I'm doing is:
1 - Create new UWP blank app
2 - Nuget -> add Akavache
3 - Nuget -> add Sqlite-net-pcl

It doesn't build.
Error:
Payload contains two or more files with the same destination path 'SQLitePCLRaw.batteries_v2.dll'. Source files: 
C:\Users\____\.nuget\packages\sqlitepclraw.bundle_e_sqlite3\1.1.0\lib\uap10.0\SQLitePCLRaw.batteries_v2.dll
C:\Users\____\.nuget\packages\sqlitepclraw.bundle_green\1.1.5\lib\uap10.0\SQLitePCLRaw.batteries_v2.dll	App2			

Any idea on how to solve this ?

**Comment by ericsink** [comment]
For this situation, I would suggest replacing sqlite-net-pcl with this:

https://www.nuget.org/packages/sqlite-net-base/

Which is the same package, by the same maintainer. except without a bundle dependency.  Which means sqlite-net will use the bundle provided by Akavache.

You do need to make sure that Akavache (and its SQLitePCL.raw bundle) gets initialized before sqlite-net tries to use it.

And also, a friendly nag to @praeclarum about releasing a non-prerelease form of sqlite-net-base.  :-)

**Comment by mesta1** [comment]
Thank you. I tried it and it is compiling, but it is crashing on calling SQLitePCL.Batteries.Initialize();
Basically after creating a new UWP app, I added the Akavache and Sqlite-net-base nuget packages.

Then on OnLaunched I added:

```
BlobCache.ApplicationName = "AkavacheExperiment";
SQLitePCL.Batteries.Init();
```
and sqlite-net-base throws this exception:

`System.TypeLoadException: 'Method 'sqlite3_bind_blob' in type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9c301db686d0bd12' does not have an implementation.'`

**Comment by helzgate** [comment]
@mesta1 Updating to the latest beta version of sqlite-net-pcl in all projects fixed this for me.  Version 1.5.166-beta

**Comment by mesta1** [comment]
Tried to update but it still gives me:
```

error APPX1101: Payload contains two or more files with the same destination path 'SQLitePCLRaw.batteries_v2.dll'. Source files: 
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1748,5): error APPX1101: C:\Users\_\.nuget\packages\sqlitepclraw.bundle_e_sqlite3\1.1.0\lib\uap10.0\SQLitePCLRaw.batteries_v2.dll
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1748,5): error APPX1101: C:\Users\_\.nuget\packages\sqlitepclraw.bundle_green\1.1.8\lib\uap10.0\SQLitePCLRaw.batteries_v2.dll
```

**Comment by helzgate** [comment]
@mesta1 Try looking at my [newtonsoft branch here](https://github.com/helzgate/xam-w-sqlite/tree/newtonsoft).  This code works although it's nowhere near a finished product.

**Comment by mesta1** [comment]
Thank you, basically the issued is solved by installing both the sqlite-net-pcl 1.5.166-beta and Akavache 6.0.0-alpha0038

Thanks for your help :)

**Comment by EmilAlipiev** [comment]
@mesta1  i dont really understand why should we use alpha version to fix this error. Before it was working wihtout any problem, what has changed? what is originally causing this problem?

**Comment by EmilAlipiev** [comment]
@ericsink  i am having the same problem for akavache and mobile center as error below shown, how can I fix that? they are even the same versions

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload contains two or more files with the same destination path 'SQLitePCLRaw.batteries_v2.dll'. Source files: 
C:\Users\user\.nuget\packages\sqlitepclraw.bundle_e_sqlite3\1.1.9\lib\uap10.0\SQLitePCLRaw.batteries_v2.dll
C:\Users\user\.nuget\packages\sqlitepclraw.bundle_green\1.1.9\lib\uap10.0\SQLitePCLRaw.batteries_v2.dll 
```

**Comment by ericsink** [comment]
I haven't tried this yet, but in the interest of a speedy reply, here's a suggestion:

Modify your package references to exclude the contents of sqlitepclraw.bundle_green.

https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#excluding-references

I'm going to test this to see if it works.

Aside to @ghuntley and @PureWeen -- on UWP, this conflict has one extra symptom that doesn't show up on other platforms, and that is a build time failure.

**Comment by ericsink** [comment]
Confirmed:  

Using Visual Studio 2017 15.5, I just created a new blank UWP app.  

Then I added Akavache 5.0.0 and Microsoft.Azure.Mobile 0.17.1.  Building the project gives the "Payload contains two or more files with the same destination path" error.

Then I added this to my csproj:

    <PackageReference Include="SQLitePCLRaw.bundle_green" Exclude="All"/>

And now the build works.

**Comment by EmilAlipiev** [comment]
I am on 6.0.0-alpha0038 version and I tried exact the same code, clean, rebuilt everything but still getting same error. I am also on VS 2015 15.5.2

![image](https://user-images.githubusercontent.com/10422347/34395535-454f5364-eb61-11e7-8137-93c824a00e96.png)

**Comment by ericsink** [comment]
Could you double check -- what version of VS are you on?

**Comment by EmilAlipiev** [comment]
as shown below

![image](https://user-images.githubusercontent.com/10422347/34395594-c64555a4-eb61-11e7-9c38-a8c00a3b0675.png)

**Comment by EmilAlipiev** [comment]
Do you have this line also together with exclude?
```
  <PackageReference Include="SQLitePCLRaw.bundle_green">
      <Version>1.1.9</Version>
    </PackageReference>
```

When I remove it manually. nuget package manager shows akavache is not installed.

**Comment by PureWeen** [comment]
Here's a sample where I messed with this and Mobile Center
https://github.com/PureWeen/Akavache.Samples/tree/master/MobileCenterApp

Maybe it's helpful?

Also I have a PR to remove the bundle dependency 
https://github.com/akavache/Akavache/pull/395
So one could just install core/sqlite3 and then just use their own bundles
Maybe it'll be eventually helpful?

**Comment by EmilAlipiev** [comment]
@PureWeen  this looks helpful. but on your sample, i dont understand something why you change forms project. I experience this problem only for uwp so far. android works fine. not tired on IOS yet. 
Btw, @ericsink  my UWP project has packages.config file, Could this be the reason excluded didnt work in cs.proj file?

**Comment by PureWeen** [comment]
change forms project?

are you referring to how I init the provider?
```
SQLitePCL.Batteries_V2.Init();
    SQLitePCL.raw.FreezeProvider();
    _LazyBlob = new Lazy<IBlobCache>(() => new SQLitePersistentBlobCache("afile.db"));
    MainPage = new MobileCenterApp.MainPage();
```

**Comment by EmilAlipiev** [comment]
opps sorry, you are using shared project. i thought it is forms project. yes also that. why these 2 lines are necessary? 

SQLitePCL.Batteries_V2.Init();
    SQLitePCL.raw.FreezeProvider();

**Comment by PureWeen** [comment]
https://github.com/ericsink/SQLitePCL.raw/wiki/Using-multiple-libraries-that-use-SQLitePCL.raw

It's a hook that Eric provided to enable different bundles uses. So the point of my sample was to show someone that used the MobileCenter nugets which use a different bundle then Akavache how to make them all work happily together

**Comment by ericsink** [comment]
Yes, the packages.config file might be causing the different behavior.
