### ISSUE TITLE
Akavache.Sqlite3 3.1.1 does not pass peverify

### ISSUE THREAD

**Issue by meteficha** [akavache/Akavache#93]
Here are the results of running `peverify` on the released binaries:

```
***** Mono/Akavache.Sqlite3.dll
Could not load class with token 2000002
* Assertion at class.c:5594, condition `!mono_loader_get_last_error ()' not met

Abort trap: 6

***** Monoandroid/Akavache.Sqlite3.dll
Missing method .ctor in assembly /Users/loyful/Downloads/Akavache.3.1.1 (1)/Monoandroid/Akavache.Sqlite3.dll, type System.Runtime.CompilerServices.AsyncStateMachineAttribute
Error: Invalid CustomAttribute content row 268 Value field 0x00000f4a
Error: CustomAttribute: Invalid constructor
Error count: 2

***** Monotouch/Akavache.Sqlite3.dll
Missing method .ctor in assembly /Users/loyful/Downloads/Akavache.3.1.1 (1)/Monotouch/Akavache.Sqlite3.dll, type System.Runtime.CompilerServices.AsyncStateMachineAttribute
Error: Invalid CustomAttribute content row 268 Value field 0x00000f4a
Error: CustomAttribute: Invalid constructor
Error count: 2

***** Net45/Akavache.Sqlite3.dll
Could not load class with token 2000002
* Assertion at class.c:5594, condition `!mono_loader_get_last_error ()' not met

Abort trap: 6

***** WinRT45/Akavache.Sqlite3.dll
Error: AssemblyRef table row 16 has invalid Flags 00000200
Error count: 1
```

AFAIU, those with `Abort trap: 6` are actually passing `peverify` since even `Xamarin.Mobile.dll` triggers this behavior.  `Monoandroid` and `Monotouch`, however, seem to have some genuine errors.

On a private Xamarin bug, Zoltan Varga stated that there were some bugs on mcs that caused some miscompilations, but that those bugs have since been fixed.  

What Xamarin.iOS version was used to compile these binaries?  (Version 7.0.2, current stable, creates binaries with the same problems.)

If you use your current setup, do your final binaries still not pass `peverify`?  If so, then I guess it's time to fill a public mcs bug report.

**Comment by flagbug** [comment]
If this is still an issue, let me know and I'll reopen this
