### ISSUE TITLE
Add Splat NuGet dependency

### ISSUE THREAD

**Issue by Haacked** [akavache/Akavache#97]
I tried calling the `DownloadUrl` extension method to `IBlobCache` but it returns a `Splat.IBitmap`. What is even a splat?

I think you just need to add a package dependency to Splat.

**Comment by flagbug** [comment]
I'm seeing Splat as dependency [here](https://github.com/akavache/Akavache/blob/e6eb0da2da6338d54e1047fa88816859e503cd4b/Akavache/akavache.nuspec#L12), so this should already be fixed, right?
